### ISSUE TITLE
Add Google's CA?

### ISSUE THREAD

**Issue by bluthen** [Lukasa/mkcert#9]
Looks like the certs are missing having Google's CA?

```
import urllib
import requests
urllib.urlretrieve("https://mkcert.org/generate/","cacert.pem")
r = requests.get('https://google.com', 'cacert.pem')
```

Throws:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by Lukasa** [comment]
What platform are you running on? What version of requests are you using?

**Comment by bluthen** [comment]
Linux 3.19.0-43 Kubuntu 15.04
requests-2.9.1
Python 2.7.9

Others verify, just not google.

**Comment by Lukasa** [comment]
What version of OpenSSL is installed on your machine, please?

**Comment by bluthen** [comment]
OpenSSL 1.0.1f 6 Jan 2014

**Comment by Lukasa** [comment]
@bluthen I suspect, then, that the problem is the same as the one in certifi/python-certifi#26 and certifi/python-certifi#32. Given that you're using requests, you should simply use the certifi module: it uses a trust bundle derived directly from mkcert.

**Comment by bluthen** [comment]
I understand. Thank you for your quick response.
